name: Allow Self-Assign for Good First Issues and Comments

on:
  issues:
    types:
      - labeled
  issue_comment:
    types:
      - created

jobs:
  self-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Allow Self-Assign on "good first issue"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue || context.payload.comment.issue; // Get issue context
            const label = context.payload.label;
            const commentBody = context.payload.comment?.body;
            
            // Check if the event is due to the label "good first issue"
            const allowedLabel = "good first issue";
            if (label && label.name === allowedLabel) {
              const assignees = issue.assignees.map(a => a.login);
              
              // Assign the user who added the label if not already an assignee
              if (!assignees.includes(issue.user.login)) {
                await github.issues.addAssignees({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  assignees: [issue.user.login],
                });
              }
            }

            // Check if the event is triggered by a comment
            if (commentBody && commentBody.trim() === "/assign") {
              const commentAuthor = context.payload.comment.user.login;
              const assignees = issue.assignees.map(a => a.login);

              // Assign the commenter if not already an assignee
              if (!assignees.includes(commentAuthor)) {
                await github.issues.addAssignees({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  assignees: [commentAuthor],
                });
              }
            }
